services:
  - type: web
    name: ultra-high-bot
    env: python
    plan: starter
    buildCommand: apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: TG_BOT_TOKEN
        sync: false
