services:
  - type: web
    name: ultra-high-bot
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: TG_BOT_TOKEN
        value: "توكن_البوت_من_BotFather"
